name: build

on:
  pull_request:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]

    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: npm install, build, and test
        run: |
          yarn --frozen-lockfile
          yarn build 
          yarn lint 
          yarn test:ci
        env:
          CI: true
#     - uses: codecov/codecov-action@v1
#       with:
#         name: jest
#         token: ${{ secrets.CODECOV_TOKEN }}
#         file: ./coverage/coverage-final.json
